[tox]

envlist =
  # Envs to build
  {linux, darwin, win32}-{py310}-{build}-{pyqt5,pyside2,pyside6}
  # Envs for metrics and development
  {linux}-{py310}-{lint}
  {linux}-{py310}-{safety}
  {linux}-{py310}-{format}
  {linux}-{py310}-{metric}
  {linux}-{py310}-{doc}
  {linux}-{py310}-{release}


skip_missing_interpreters =
  true

[gh-actions]
python =
    3.10: py310

[gh-actions:env]
PLATFORM =
    ubuntu-latest: linux
    macos-latest: darwin
    windows-latest: win32

TASK =
    build: build
    lint: lint
    safety: safety
    format: format
    metric: metric
    doc: doc
    release: release

[testenv]

platform =
  # platforms to run
  win: win32
  lin: linux
  mac: osx

deps =
  build: -rreq-stable.txt
  test: -rreq-test.txt
  lint: -rreq-test.txt
  safety: -rreq-test.txt
  format: -rreq-test.txt
  metric: -rreq-test.txt
  doc: -rreq-doc.txt
  release: -rreq-release.txt

  # basic dependencies for each env
  pyqt5: pyqt5
  pyside2: pyside2
  pyside6: pyside6

whitelist_externals =
  # non python dependencies
  qmake
  doc: make
  doc: latexpdf

changedir=
  doc: docs

commands =
  python -m pip install --upgrade pip

  # check depedencies
  pip check
  # list all deps
  pip list

  # BUILD ------------------------------------------------------------------

  # try generate build
  build: python setup.py sdist bdist_wheel
  # try install with pip
  build: pip install .
  # get some info
  build: python -m qrainbowstyle --all

  # need to run the interface to certify the build, run example
  build-pyqt5: python example/example.py --qt_from=pyqt5 --test

  build-pyside2: python example/example.py --qt_from=pyside2 --test

  build-pyside6: python example/example.py --qt_from=pyside6 --test

  # TEST -------------------------------------------------------------------

  # Those commands commented below correct style problems
  # DO NOT RUN ON SERVER, it is just to keep registry for local use
  # autopep8 --ignore=E501 --aggressive --aggressive --aggressive --experimental
  # docformatter -r -i --wrap-summaries=0 --wrap-descriptions=0 *.py
  # eradicate

  # Test and coverage
  # test: pytest --cov "./tests"
  test: pytest --cov

  # Code and docstring style check, running alone for now - pylama-#156
  # test: pylama -v --options="tox.ini" "{toxinidir}"

  # Linting and formatting
  lint: ruff check .
  format: ruff format .

  # Safety
  safety: safety check

  # Code metrics
  metric: radon cc -a qrainbowstyle --exclude="*/ui/*" --exclude="*/styles/*"
  metric: radon mi qrainbowstyle --exclude="*/ui/*" --exclude="*/styles/*"
  metric: radon raw -s qrainbowstyle --exclude="*/ui/*" --exclude="*/styles/*"
  metric: radon hal -f qrainbowstyle --exclude="*/ui/*" --exclude="*/styles/*"

  # DOC (inside docs folder) ----------------------------------------------

  # Documentation - generate apidocs, build html, build latex, build pdf
  doc: sphinx-apidoc --private --separate --force --module-first -o "example" "{toxworkdir}/../example" "{toxworkdir}/../example/ui/*"
  doc: sphinx-apidoc --private --separate --force --module-first -o "reference" "{toxworkdir}/../qrainbowstyle"
  doc: sphinx-apidoc --private --separate --force --module-first -o "scripts" "{toxworkdir}/../scripts"
  
  doc: sphinx-build -b html -j auto -E -d "{toxworkdir}/../build/docs/doctrees" . "{toxworkdir}/../build/docs/html"

  # RELEASE -------------------------------------------------------------------------------
  # Try to use re-ver package
  release: python setup.py clean --all
  release: python setup.py sdist bdist_wheel
  release: python setup.py check -s -r # even deprecated, shows better error messages that are passing in twine
  release: twine check dist/*


usedevelop =
  develop: true


# MYPY #######################################################################

[mypy]
# general configuration

[mypy-numpy]
ignore_missing_imports = True

[mypy-qtpy]
ignore_missing_imports = True

[mypy-scipy]
ignore_missing_imports = True

[mypy-pint]
ignore_missing_imports = True

[mypy-spyder]
ignore_missing_imports = True

[mypy-networkx]
ignore_missing_imports = True

[mypy-qrainbowstyle]
ignore_missing_imports = True

[mypy-jsonpickle]
ignore_missing_imports = True
